app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine.dbal:
    default_connection: default
    dbname:             symfony
    user:               root
    password:           root

doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        ProductBundle: 
            type: annotation
            dir: Entity/
        StoreBundle: 
            type: annotation
            dir: Entity/
        ReviewBundle: 
            type: annotation
            dir: Entity/

parameters:
    productbundle.product.review: Bundle\ReviewBundle\Entity\Review
    reviewbundle.review.product: Bundle\ProductBundle\Entity\Product
    productbundle.product.customer: Bundle\ReviewBundle\Entity\Review

services:
    tableprefix:
        class: DoctrineExtensions\TablePrefixListener
        arguments: [local_]
        tags:
            - { name: doctrine.dbal.default_event_listener, event: loadClassMetadata, method: loadClassMetadata }
    dynamic_targets:
        class: Application\JonTestBundle\AssociationListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.dbal.default_event_listener, event: loadClassMetadata }

## Swiftmailer Configuration
swiftmailer.config:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   jtownsend54@gmail.com
    password:   j)rdan23

# Asset Packager Bundle
assetpackager.config:
    js: # Javascript Config
        packages: # Javascript Packages
            pack1: # Package Name
                - bundles/bundle/js/pack1.js
                - bundles/bundle/js/pack1_1.js
    css: # Stylesheet Config
        packages: # Stylesheet Packages
            pack1: # Package Name
                compressor:
                    id: cssmin
                    options: 
                        compress-unit-values: true
                paths:
                - bundles/bundle/css/pack1.css
                - bundles/bundle/css/pack1_1.css
