homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

bridal:
    resource: JonTestBundle/Resources/config/routing.yml

products:
    resource: JonTestBundle/Resources/config/routing.yml

drilldown:
    resource: JonTestBundle/Resources/config/routing.yml