homepage:
    pattern:  /
    defaults: { _controller: JonTestBundle:Content:index }

products:
    resource: JonTestBundle/Resources/config/routing.yml

# app/config/routing.yml
_assetpackager:
    resource: Tecbot/AssetPackagerBundle/Resources/config/routing.yml
    prefix:   /_ap