homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

bridal:
    resource: JonTestBundle/Resources/config/routing.yml

products:
    resource: JonTestBundle/Resources/config/routing.yml

# app/config/routing.yml
_assetpackager:
    resource: Tecbot/AssetPackagerBundle/Resources/config/routing.yml
    prefix:   /_ap