products:
    pattern:  /products/category/{categoryName}
    defaults: { _controller: JonTestBundle:Products:index }

product:
    resource: ProductBundle/Resources/config/routing.yml

ajaxtest:
    pattern: /ajaxtest
    defaults: { _controller: JonTestBundle:Content:ajax }