hello:
    pattern:  /hello/{name}
    defaults: { _controller: JonTestBundle:JonTest:index }

bridal:
    pattern:  /bridal/
    defaults: { _controller: JonTestBundle:JonTest:index }

baby:
    pattern:  /baby/
    defaults: { _controller: JonTestBundle:JonTest:index }

birthday:
    pattern:  /birthday/
    defaults: { _controller: JonTestBundle:JonTest:index }